---
- name: Deploy docker images
  # hosts: all
  hosts: localhost

  tasks:
    # - name: Copy Docker Compose file from host machine to remote host
    #   copy:
    #     src: ./docker-compose.yml
    #     dest: ./
        
    - name: Pull the Docker images specifed in docker-compose
      shell: 
        cmd: /usr/local/bin/docker-compose pull
        chdir: ./
      
    - name: Run the pulled Docker images in detached mode
      command: /usr/local/bin/docker-compose up -d --build

    - name: Prune unwanted images
      command: /usr/local/bin/docker image prune --force
# ---
# - name: Deploy docker images
#   hosts: localhost

#   tasks:
#     - name: Copy Docker Compose file from host machine to remote host
#       copy:
#         src: ./docker-compose.yml
#         dest: ./
        
#     - name: Run the pulled Docker images in detached mode
#       command: /usr/local/bin/docker-compose up -d --build