---
- name: Deploy docker images
  hosts: all
  # hosts: localhost

  tasks:
    - name: Copy Docker Compose file from host machine to remote host
      copy:
        src: ./docker-compose.yml
        dest: ./
    
    - name: Replace Jinja2 template with decrypted environment variables into env.yaml file
      template: 
        src: backend/.env
        dest: .env
        
    - name: Pull the Docker images specifed in docker-compose
      shell: 
        cmd: docker-compose pull
        chdir: ./

    # We don't start the containers because we need to copy the env.yaml file into the backend container
    # before we can start anything.
    # So we first create the containers so that the next command "docker cp" can run properly
    - name: Create containers for the pulled Docker images
      command: docker-compose up --no-start

    - name: Copy the env.yaml file to backend Docker container
      command: docker cp .env rahul_backend_1:/usr/src/app/.env

      
    - name: Run the pulled Docker images in detached mode
      command: docker-compose up -d --build

    - name: Prune unwanted images
      command: docker image prune --force
# ---
# - name: Deploy docker images
#   hosts: localhost

#   tasks:
#     - name: Copy Docker Compose file from host machine to remote host
#       copy:
#         src: ./docker-compose.yml
#         dest: ./
        
#     - name: Run the pulled Docker images in detached mode
#       command: /usr/local/bin/docker-compose up -d --build