version: '3.5'
services:
  backend:
    # image: rj2332/mern-app:backend
    image: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      
  frontend:
    # image: rj2332/mern-app:frontend
    image: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

    volumes:
      - ./data/db:/data/db:rw


# version: '3.5'
# services:
#   backend:
#     image: backend
#     ports:
#       - "4000:4000"
#     depends_on:
#       - mongodb
      
#   frontend:
#     image: frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

#   mongodb:
#     image: mongo
#     ports:
#       - "27017:27017"
    # volumes:
    #   - /Users/rahuljain/Documents/Semester7/SPE/MajorProject/MERN-Auth-Tutorial-lesson-17/data/db:/data/db:rw